version: '3.9'

services:
  db:
    #コンテナの名前
    container_name: rkswk-dokcer-db
    #イメージのビルド
    build:
      dockerfile: db/Dockerfile
      context: .
    #container run --mount で指定していたボリュームのマウントも volumes: で置き換え
    volumes:
      - type: volume
        #作成したボリューム名 
        source: rkswk-docker-db-volume 
        #実際のMySQLデーターベース
        target: /var/lib/mysql
      #バインドマウント
      #- type: bind
      #  source: ./docker/db/init.sql
      #  target: /docker-entrypoint-initdb.d/init.sql
    #環境変数の指定
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: ryokawasaki
      MYSQL_PASSWORD: rkswk
      MYSQL_DATABASE: rkswk
    ports:
      - 4306:3306

  php:
    #コンテナの名前
    container_name: rkswk-dokcer-php-app
    #イメージのビルド
    build:
      dockerfile: php/Dockerfile
      context: .
    ports:
      - '18000:8000'
    volumes:
      - type: bind
        source: ./php/src
        target: /src
    command: php -S 0.0.0.0:8000 -t /src

  mail:
    #コンテナの名前
    container_name: rkswk-dokcer-mail
    image: mailhog/mailhog:v1.0.1
    platform: linux/x86_64
    ports:
      - "18025:8025"

  rails:
    #コンテナの名前
    container_name: rkswk-dokcer-rails-app
    tty: true
    depends_on:
      - db
    build:
      dockerfile: rails/Dockerfile
      context: .
    ports:
      - 13000:3000
    volumes:
      - type: bind
        source: ./rails
        target: /app
    #command: rails server -b 0.0.0.0
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  front:
    #コンテナの名前
    container_name: rkswk-dokcer-front
    #イメージのビルド
    build:
      dockerfile: front/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./front/app
        target: /usr/src/app
    command: 'yarn dev'
    ports:
      - "28000:3000"

#docker volume createの作成を volumes: に変換
volumes:
  rkswk-docker-db-volume: